spring:
    datasource:
        url: jdbc:h2:mem:championsleague
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show_sql: true
        hibernate:
            ddl-auto: create
            naming:
              strategy: org.hibernate.cfg.ImprovedNamingStrategy
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    http:
        multipart:
            max-file-size: 128KB
            max-request-size: 128KB